ci: add build GitHub action (#90)
Signed-off-by: PoAn Yang <poan.yang@suse.com>

diff --git a/package/Dockerfile b/package/Dockerfile
--- a/package/Dockerfile
+++ b/package/Dockerfile
@@ -1,11 +1,17 @@
-FROM registry.suse.com/bci/bci-base:15.4
+FROM registry.suse.com/bci/bci-base:15.5
+
+ARG TARGETPLATFORM
+RUN if [ "$TARGETPLATFORM" != "linux/amd64" ] && [ "$TARGETPLATFORM" != "linux/arm64" ]; then \
+    echo "Error: Unsupported TARGETPLATFORM: $TARGETPLATFORM" && \
+    exit 1; \
+    fi
 
 # hadolint ignore=DL3037
 RUN zypper -n rm container-suseconnect && \
     zypper -n install unzip curl vim && \
     zypper -n clean -a && rm -rf /tmp/* /var/tmp/* /usr/share/doc/packages/*
 
-ARG ARCH=amd64
+ENV ARCH ${TARGETPLATFORM#linux/}
 ENV KERNEL_ARCH linux_${ARCH}
 # install terraform
 ENV TERRAFORM_VERSION 1.4.6
@@ -20,7 +26,7 @@ ARG PROVIDER_VERSION=0.0.0-dev
 ENV PROVIDERS_DIR /root/.terraform.d/plugins/terraform.local/local/harvester
 ENV PROVIDER_DIR ${PROVIDERS_DIR}/${PROVIDER_VERSION}/${KERNEL_ARCH}
 RUN mkdir -p ${PROVIDER_DIR}
-COPY ./terraform-provider-harvester ${PROVIDER_DIR}/terraform-provider-harvester_v${PROVIDER_VERSION}
+COPY ./terraform-provider-harvester-${ARCH} ${PROVIDER_DIR}/terraform-provider-harvester_v${PROVIDER_VERSION}
 RUN mkdir -p /data
 COPY ./provider.tf /data/provider.tf
 WORKDIR /data
